### ISSUE TITLE
needs (automated) tests!!

### ISSUE THREAD

**Issue by yarikoptic** [dpisner453/PyNets#9]
ATM lacks any automated testing -- unit tests, integration with CIs (travis etc)

**Comment by dpisner453** [comment]
Working on it. Stay tuned.

**Comment by dpisner453** [comment]
See development branch.  Now equipped with travis-ci testing/ pytest, etc. Also, reformatted using cookie-cutter, plus pynets is now more organized and importable.

Unit tests nearly complete for nodemaker.py module, and working on the others.

Thanks for the suggestions!
